---
swagger: "2.0"
info:
  description: A tracking app on who cooks and who eats that day
  title: Cook2Share
  version: 1.0.0
schemes:
- http
paths:
  /meals:
    get:
      tags:
        - meals
      operationId: getMeals
      parameters:
        - name: date
          in: query
          type: string
          format: date
        - name: limit
          in: query
          type: integer
          minimum: 1
          maximum: 50
        - name: daysforward
          in: query
          type: integer
          minimum: 0
          maximum: 365
      responses:
        200:
          description: An array of json objects representing the days
          schema:
            type: array
            items:
              $ref: "#/definitions/meal"
        default:
          description: Generic error
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - meals
      operationId: insertOne
      parameters:
        - name: body
          in: body
          required: true  
          schema: 
            $ref: "#/definitions/meal"
      responses:
        201:
          description: An indication of successful insert.
        default:
          description: Generic error
          schema:
            $ref: "#/definitions/error"
          
definitions:
  meal:
    type: object
    properties:
      mealId: 
        type: integer
        format: int64
      mealType:
        type: string
      mealAuthorId: 
        type: integer
        format: int64
      mealDate:
        type: string
        format: date
      mealName:
        type: string
      kcalories:
        type: integer
        format: int64
      consumerIds:
        type: array
        items:
          type: integer
          format: int64
  user:
    type: object
    properties:
      userId:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string