---
swagger: "2.0"
info:
  description: A tracking app on who cooks and who eats that day
  title: Cook2Share
  version: 1.0.0
schemes:
- http
paths:
  /meals:
    get:
      tags:
        - meals
      operationId: getMeals
      parameters:
        - name: date
          in: query
          type: string
          format: date
        - name: limit
          in: query
          type: integer
          minimum: 1
          maximum: 50
      responses:
        200:
          description: An array of json objects representing the days
          schema:
            type: array
            items:
              $ref: "#/definitions/meal"
        default:
          description: Generic error
          schema:
            $ref: "#/definitions/error"
  /:
    get:
      tags:
        - todos
      operationId: findTodos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - todos
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - todos
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  meal:
    type: object
    properties:
      mealId: 
        type: integer
        format: int64
      mealType:
        type: string
      mealAuthor: 
        type: string
      mealDate:
        type: string
        format: date
      mealName:
        type: string
      kcalories:
        type: integer
        format: int64
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string